{% set version = "0.6.1" %}
{% set sha256 = "b6a107ab06206acc5359d4c5632bd9b22d448702a79b3169b0c62e0fb808bb2a" %}

package:
  name: python-snappy
  version: {{ version }}

source:
  fn: python-snappy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/python-snappy/python-snappy-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - snappy
    - msinttypes  # [win and py27]
  run:
    - python
    - snappy

test:
  imports:
    - snappy

about:
  home: https://github.com/andrix/python-snappy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for the snappy compression library from Google
  dev_url: https://github.com/andrix/python-snappy

extra:
  recipe-maintainers:
    - mariusvniekerk
    - martindurant
    - djsutherland
