{% set version = "0.7.1" %}
{% set sha256 = "1bc29d36211d44bb9f04f3d7ccfbaeaebbc2f62b6d40f4fc4edd1fb16bc52c13" %}

package:
  name: python-snappy
  version: {{ version }}

source:
  fn: python-snappy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/python-snappy/python-snappy-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cramjam
  run:
    - python >=3.8
    - cramjam

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - snappy

about:
  home: https://github.com/intake/python-snappy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for the snappy compression library from Google
  dev_url: https://github.com/intake/python-snappy

extra:
  recipe-maintainers:
    - mariusvniekerk
    - martindurant
    - djsutherland
