travis:
  secure:
    BINSTAR_TOKEN: rBtJGXoTptudKbBMY8GoflMDrLMrsmY3H6+oyB/8DyrCTJ4YEceXS/o8s65XOucYuSUeACZu6sFbnJI/a1p1PCbEJ4i+3G1QXgZe9dduZzdZZNH1i+6l45YZSs29Twb2TolPMOVGbkVs471w9jEsKc/gHpXDP6HHROiNWlGquuKO+bAE9n5yB1cRVtP75OfpWtHO1+1p2eG8BxG6LODR9UYZLeQd2jXikCTPTMF/hiJtVTRghdcXiSbL8SlGSES7rckduJHo8M/FZRCqO6+6vsTkLs6jHICqK3n2nDj7K0Tm2VVcaeeHMc/aMSuPsrbTTnR535fLFexN7XVfMKvCgGOd41ff0+ESHlsabbUECADECcBgEBt6LW5OkSnsig2DAlgdDPyhcnR6odEHL9IZQWbEJPSD9uZpAEaQca3XcNRdkzAQgxEGN9kTIGNCxR5udAl2/xoFqgsLgmG4+9BWb0uFYCNLUMgGKzRmdrG7Q8p7dv/irDe+k4JkNuiZItn/UFHgzSjBKL1TGCLVl6cHdYwotXIkkJ5BaGkb/VUeIVsOarFR9d5L3cK+MOFJU3YN/IfOuRg1c0wAYmJE89aJAS3AstEQDzHh44zT7hUgZWXDcrwu+ZHVQ8H2iMJqBlHIr22b33HZtesBhVq5iKTUR+nPo5qkSkdyeL35ddrl4kA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
